### PR TITLE
PSR-4 namespaces

### PR DESCRIPTION
**Pull request by hotmeteor**
This updates any misspelled or incorrect test namespaces so we meet PSR-4 standards, and can use Composer 2.

### CODE REVIEW

**Comment by stevespur** [comment]
we may need to test this and add a migration, I want to say we tried to fix the casing before and it caused a problem

**Comment by hotmeteor** [comment]
@stevespur Can you advise on what migrations we may need?

**Comment by hotmeteor** [comment]
@stevespur We could also tag this as a minor update... 2.4.

**Comment by stevespur** [comment]
the only ones we have records for are `PhiladelphiaLocalEITTax` and it looks like those are capitalized the same was as the file. It may have been issues with the local withholding report when we tried to run the report for a tax that changed casing. @Aidancs do you remember this at all?

**Comment by stevespur** [comment]
I'd say this is significant enough to be a `2.4` instead a `2.3.11`

**Comment by Aidancs** [comment]
@stevespur I think this is different. If I am thinking the same it was the `seperate` in code that should have been  ` separate` that wasn't changed because it _could_ cause problems, I think the namespacing is different and shouldn't affect anything. But you could be thinking something different 

@hotmeteor I noticed that there are some migrations that are being changed, I thought we didn't change old migrations, we made new ones to update instead

**Comment by hotmeteor** [comment]
@Aidancs Good catch. Normally we wouldn't, but in this case it's OK. This is also a good case study for why we shouldn't really be referencing classes/objects in our migrations that could change at a later point.

**Comment by hotmeteor** [comment]
@stevespur @Aidancs Are you OK with me merging and tagging this then?

**Comment by Aidancs** [comment]
Shouldn't we put this on a Spur PR for Tasie to test?

**Comment by hotmeteor** [comment]
@Aidancs I don't think we need to. Sounds like none of the affected tax classes are being used.

**Pull request merged**
